apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: falco

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
subjects:
  - kind: ServiceAccount
    name: falco
    namespace: falco

roleRef:
  kind: ClusterRole
  name: falco
  apiGroup: rbac.authorization.k8s.io